### ISSUE TITLE
Unexpected token {

### ISSUE THREAD

**Issue by binarykitchen** [vadimdemedes/trevor#64]
```
└─❱❱❱ trevor                                                                                                                                                                        +4054 10:48 ❰─┘
/usr/local/lib/node_modules/trevor/cli.js:8
const {STATE_ERROR} = require('./lib/states');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

using node.js v4.4.5 here

**Comment by SamVerschueren** [comment]
You need to upgrade to Node 6.x

**Comment by binarykitchen** [comment]
then mention this in the readme

**Comment by vadimdemedes** [comment]
You should've seen a warning message when installing this package, because package.json has the correct version range for Node.js.
